on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: '16.x'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Deploy files
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/var/www/playground"
